### ISSUE TITLE
Add check for healthy engine

### ISSUE THREAD

**Issue by StLuke** [StLuke/rhevm-ansible#12]
Check:
1. Database is up
2. Engine service is up
3. Engine service is up after restart
3. wait for Health status OK ->  GET http://engine.com:80/OvirtEngineWeb/HealthStatus - CODE: 200,

**Comment by lukas-bednar** [comment]
that `http://{fqdn}/OvirtEngineWeb/HealthStatus` is deprecated please use `http://{fqdn}/ovirt-engine/services/health` instead.
