### ISSUE TITLE
Installing libselinux-python on hosts

### ISSUE THREAD

**Issue by pkubica** [StLuke/rhevm-ansible#6]
Now role **engine-install** need package **libselinux-python** on the host.
 - When prompting _engine-setup_, it fail on selinux without this package but installing other packages on host may be not a good idea for solving this issue.

- file: /roles/common/tasks/main.yml 
tasks: install libselinux-python for ansible

**Comment by StLuke** [comment]
If you have SELinux enabled on remote nodes, you will also want to install libselinux-python on them before using any copy/file/template related functions in Ansible. You can of course still use the yum module in Ansible to install this package on remote systems that do not have it.
